process.env.YELP_CLIENT_ID = "KeZmfAGKpXJhhEt6j8kZjw"
process.env.YELP_CLIENT_SECRET = "MHqEzHTnbp1wkNvL2MJrZIW0NlPHWne4KHVpanj3e0TZgxXqvdzMKj3rcM8rKWiv"
process.env.YELP_TOKEN = "uzqAy7ItjidoEOeIPsqGrslQKnOM2XGhVEJMxpj6iUqNZgXor3NXmdPeqJ1x21ZAuJjhzVqBcsjpby6oFg_fF-SppgerPUwIIt1ggIiY21-9HIY2YdqSp6WX2NiMWXYx"
